-- ColeFinder – Schema (PROD / public)
-- Ejecutar en: SQL Editor de Supabase
-- Requisitos: proyecto Supabase nuevo con extensión PostGIS activada
-- Orden global: public/01 → staging/01 → public/02 → staging/02 → …

-- =============================================================================
-- Extensiones (PostGIS es obligatorio para geography y el índice GIST)
-- =============================================================================
-- En Supabase Cloud, activa PostGIS desde Database → Extensions antes de ejecutar este script.
CREATE EXTENSION IF NOT EXISTS postgis;
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- =============================================================================
-- Tipos enumerados
-- =============================================================================
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_type t
    JOIN pg_namespace n ON n.oid = t.typnamespace
    WHERE n.nspname = 'public' AND t.typname = 'app_update_type'
  ) THEN
    CREATE TYPE public.app_update_type AS ENUM ('FLEXIBLE', 'IMMEDIATE');
  END IF;
END $$;

-- =============================================================================
-- Tabla colegios — centros educativos geolocalizados
-- =============================================================================
CREATE TABLE IF NOT EXISTS public.colegios (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre text NOT NULL,
  direccion text,
  latitud double precision NOT NULL,
  longitud double precision NOT NULL,
  tipo text DEFAULT 'Público'::text,
  localidad text,
  fuente text,
  fuente_id bigint NOT NULL,
  descripcion_entidad text,
  descripcion text,
  content_url text,
  clase_vial text,
  nombre_via text,
  tipo_num text,
  num text,
  codigo_postal text,
  provincia text,
  barrio text,
  cod_barrio integer,
  distrito text,
  cod_distrito integer,
  telefono text,
  fax text,
  email text,
  accesibilidad smallint,
  categoria_madrid text,
  tipo_centro_normalizado text,
  titularidad_normalizada text,
  location geography(Point, 4326),
  es_dificil_desempeno boolean NOT NULL DEFAULT false,
  jornada_tipo text NOT NULL DEFAULT 'desconocida'::text,
  es_rural boolean NOT NULL DEFAULT false,
  CONSTRAINT colegios_jornada_tipo_check CHECK (
    jornada_tipo = ANY (ARRAY['continua'::text, 'partida'::text, 'desconocida'::text])
  )
);

COMMENT ON TABLE public.colegios IS 'Centros educativos importados de fuentes públicas (Ministerio, CCAA, open data).';
COMMENT ON COLUMN public.colegios.location IS 'Punto geography WGS84; se rellena con trigger desde latitud/longitud.';
COMMENT ON COLUMN public.colegios.tipo_centro_normalizado IS 'PRIMARIA | SECUNDARIA | FP | ADULTOS | ESPECIAL | OTROS';
COMMENT ON COLUMN public.colegios.titularidad_normalizada IS 'PUBLICO | CONCERTADO | PRIVADO | OTRO';

-- Unicidad por fuente de importación (clave para ON CONFLICT en seeds)
CREATE UNIQUE INDEX IF NOT EXISTS colegios_fuente_fuente_id_key
  ON public.colegios USING btree (fuente, fuente_id);

-- Índice espacial KNN (<->) usado por nearby_colegios
CREATE INDEX IF NOT EXISTS idx_colegios_location
  ON public.colegios USING gist (location);

CREATE INDEX IF NOT EXISTS idx_colegios_titularidad
  ON public.colegios USING btree (titularidad_normalizada);

CREATE INDEX IF NOT EXISTS idx_colegios_tipo_centro
  ON public.colegios USING btree (tipo_centro_normalizado);

-- =============================================================================
-- Tabla app_config — parámetros remotos (actualizaciones, límite RPC, etc.)
-- =============================================================================
CREATE TABLE IF NOT EXISTS public.app_config (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  key text NOT NULL,
  value text NOT NULL,
  updated_at timestamptz NOT NULL DEFAULT now(),
  value_enum public.app_update_type,
  CONSTRAINT app_config_key_key UNIQUE (key),
  CONSTRAINT public_app_config_update_type_check CHECK (
    key <> 'update_type' OR value = ANY (ARRAY['FLEXIBLE'::text, 'IMMEDIATE'::text])
  ),
  CONSTRAINT public_app_config_nearby_limit_check CHECK (
    key <> 'nearby_colegios_limit' OR value ~ '^[0-9]+$'::text
  ),
  CONSTRAINT public_app_config_min_version_check CHECK (
    key <> 'min_version_code' OR value ~ '^[0-9]+$'::text
  ),
  CONSTRAINT public_app_config_value_enum_usage CHECK (
    (key = 'update_type' AND value_enum IS NOT NULL)
    OR (key <> 'update_type' AND value_enum IS NULL)
  )
);

COMMENT ON TABLE public.app_config IS 'Configuración remota key/value. update_type usa value_enum (selector en Supabase).';
COMMENT ON COLUMN public.app_config.value_enum IS 'Solo para key=update_type; el trigger copia a value para la app.';

-- =============================================================================
-- Funciones de trigger (deben existir antes de crear los triggers)
-- =============================================================================

-- Rellena geography.location al insertar/actualizar latitud o longitud
CREATE OR REPLACE FUNCTION public.handle_colegios_location()
RETURNS trigger
LANGUAGE plpgsql
SET search_path TO public, extensions
AS $function$
BEGIN
  IF NEW.latitud IS NOT NULL AND NEW.longitud IS NOT NULL THEN
    NEW.location := ST_SetSRID(ST_MakePoint(NEW.longitud, NEW.latitud), 4326)::geography;
  ELSE
    NEW.location := NULL;
  END IF;
  RETURN NEW;
END;
$function$;

-- Sincroniza value_enum → value para update_type; limpia value_enum en otras claves
CREATE OR REPLACE FUNCTION public.app_config_sync_value_enum()
RETURNS trigger
LANGUAGE plpgsql
SET search_path TO public
AS $function$
BEGIN
  IF NEW.key = 'update_type' THEN
    IF NEW.value_enum IS NOT NULL THEN
      NEW.value := NEW.value_enum::text;
    ELSIF NEW.value IS NOT NULL AND NEW.value IN ('FLEXIBLE', 'IMMEDIATE') THEN
      NEW.value_enum := NEW.value::public.app_update_type;
    END IF;
  ELSE
    NEW.value_enum := NULL;
  END IF;
  NEW.updated_at := now();
  RETURN NEW;
END;
$function$;

-- =============================================================================
-- Triggers
-- =============================================================================
DROP TRIGGER IF EXISTS tr_colegios_location_update ON public.colegios;
CREATE TRIGGER tr_colegios_location_update
  BEFORE INSERT OR UPDATE OF latitud, longitud ON public.colegios
  FOR EACH ROW
  EXECUTE FUNCTION public.handle_colegios_location();

DROP TRIGGER IF EXISTS trg_public_app_config_sync_value_enum ON public.app_config;
CREATE TRIGGER trg_public_app_config_sync_value_enum
  BEFORE INSERT OR UPDATE ON public.app_config
  FOR EACH ROW
  EXECUTE FUNCTION public.app_config_sync_value_enum();

-- =============================================================================
-- Row Level Security — solo lectura para roles de la app
-- =============================================================================
ALTER TABLE public.colegios ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.app_config ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS colegios_select_anon ON public.colegios;
CREATE POLICY colegios_select_anon ON public.colegios
  FOR SELECT TO anon
  USING (true);

DROP POLICY IF EXISTS colegios_select_authenticated ON public.colegios;
CREATE POLICY colegios_select_authenticated ON public.colegios
  FOR SELECT TO authenticated
  USING (true);

DROP POLICY IF EXISTS public_app_config_select_anon ON public.app_config;
CREATE POLICY public_app_config_select_anon ON public.app_config
  FOR SELECT TO anon
  USING (true);

DROP POLICY IF EXISTS public_app_config_select_authenticated ON public.app_config;
CREATE POLICY public_app_config_select_authenticated ON public.app_config
  FOR SELECT TO authenticated
  USING (true);

-- =============================================================================
-- Permisos de tabla (PostgREST / rol anon)
-- =============================================================================
GRANT USAGE ON SCHEMA public TO anon, authenticated;
GRANT SELECT ON TABLE public.colegios TO anon, authenticated;
GRANT SELECT ON TABLE public.app_config TO anon, authenticated;
