-- ColeFinder – Schema (PRE / staging)
-- Ejecutar después de public/01_schema.sql (comparte enum public.app_update_type y función app_config_sync_value_enum)
-- Replica el esquema staging actual: sin PK en colegios, índices con prefijo idx_staging_*

-- ⚠️  PASO PREVIO OBLIGATORIO ANTES DE EJECUTAR ESTE SCRIPT
-- ─────────────────────────────────────────────────────────────────────
-- supabase.com (hosted): el esquema "staging" no está expuesto por
-- defecto. Sin este paso la app PRE falla con error 406 (Not Acceptable).
--
-- 1. Supabase Studio → icono Configuración (⚙️ esquina inferior izquierda)
-- 2. Menú "INTEGRATIONS" → clic en "Data API"
-- 3. Pestaña central "Settings"
-- 4. Apartado "Exposed Schemas" → añadir: staging  (junto a public)
-- 5. Guardar cambios y esperar ~10 segundos a que reinicie la API
--
-- Self-hosted: añadir "staging" a PGRST_DB_SCHEMAS en config.toml
--   db-extra-search-path = "public, staging"
-- ─────────────────────────────────────────────────────────────────────

-- =============================================================================
-- Esquema staging
-- =============================================================================
CREATE SCHEMA IF NOT EXISTS staging;
GRANT USAGE ON SCHEMA staging TO anon, authenticated;

-- =============================================================================
-- Tabla colegios (PRE) — misma estructura que public; unicidad por (fuente, fuente_id)
-- =============================================================================
CREATE TABLE IF NOT EXISTS staging.colegios (
  id integer GENERATED BY DEFAULT AS IDENTITY,
  nombre text NOT NULL,
  direccion text,
  latitud double precision NOT NULL,
  longitud double precision NOT NULL,
  tipo text DEFAULT 'Público'::text,
  localidad text,
  fuente text,
  fuente_id bigint NOT NULL,
  descripcion_entidad text,
  descripcion text,
  content_url text,
  clase_vial text,
  nombre_via text,
  tipo_num text,
  num text,
  codigo_postal text,
  provincia text,
  barrio text,
  cod_barrio integer,
  distrito text,
  cod_distrito integer,
  telefono text,
  fax text,
  email text,
  accesibilidad smallint,
  categoria_madrid text,
  tipo_centro_normalizado text,
  titularidad_normalizada text,
  location geography(Point, 4326),
  es_dificil_desempeno boolean NOT NULL DEFAULT false,
  jornada_tipo text NOT NULL DEFAULT 'desconocida'::text,
  es_rural boolean NOT NULL DEFAULT false,
  CONSTRAINT colegios_jornada_tipo_check CHECK (
    jornada_tipo = ANY (ARRAY['continua'::text, 'partida'::text, 'desconocida'::text])
  ),
  CONSTRAINT colegios_fuente_fuente_id_key UNIQUE (fuente, fuente_id)
);

COMMENT ON TABLE staging.colegios IS 'Centros educativos (entorno PRE). location se rellena en import/seed (sin trigger en staging en producción).';

CREATE INDEX IF NOT EXISTS idx_staging_colegios_location
  ON staging.colegios USING gist (location);

CREATE INDEX IF NOT EXISTS idx_staging_colegios_titularidad
  ON staging.colegios USING btree (titularidad_normalizada);

CREATE INDEX IF NOT EXISTS idx_staging_colegios_tipo_centro
  ON staging.colegios USING btree (tipo_centro_normalizado);

-- =============================================================================
-- Tabla app_config (PRE)
-- =============================================================================
CREATE TABLE IF NOT EXISTS staging.app_config (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  key text NOT NULL,
  value text NOT NULL,
  updated_at timestamptz NOT NULL DEFAULT now(),
  value_enum public.app_update_type,
  CONSTRAINT app_config_key_key UNIQUE (key),
  CONSTRAINT staging_app_config_update_type_check CHECK (
    key <> 'update_type' OR value = ANY (ARRAY['FLEXIBLE'::text, 'IMMEDIATE'::text])
  ),
  CONSTRAINT staging_app_config_nearby_limit_check CHECK (
    key <> 'nearby_colegios_limit' OR value ~ '^[0-9]+$'::text
  ),
  CONSTRAINT staging_app_config_min_version_check CHECK (
    key <> 'min_version_code' OR value ~ '^[0-9]+$'::text
  ),
  CONSTRAINT staging_app_config_value_enum_usage CHECK (
    (key = 'update_type' AND value_enum IS NOT NULL)
    OR (key <> 'update_type' AND value_enum IS NULL)
  )
);

-- =============================================================================
-- Trigger app_config — reutiliza la función en public (como en producción)
-- =============================================================================
DROP TRIGGER IF EXISTS trg_staging_app_config_sync_value_enum ON staging.app_config;
CREATE TRIGGER trg_staging_app_config_sync_value_enum
  BEFORE INSERT OR UPDATE ON staging.app_config
  FOR EACH ROW
  EXECUTE FUNCTION public.app_config_sync_value_enum();

-- =============================================================================
-- Row Level Security (políticas actuales en staging)
-- =============================================================================
ALTER TABLE staging.colegios ENABLE ROW LEVEL SECURITY;
ALTER TABLE staging.app_config ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS staging_colegios_select_anon ON staging.colegios;
CREATE POLICY staging_colegios_select_anon ON staging.colegios
  FOR SELECT TO anon
  USING (true);

DROP POLICY IF EXISTS staging_app_config_select_anon ON staging.app_config;
CREATE POLICY staging_app_config_select_anon ON staging.app_config
  FOR SELECT TO anon
  USING (true);

DROP POLICY IF EXISTS staging_app_config_select_authenticated ON staging.app_config;
CREATE POLICY staging_app_config_select_authenticated ON staging.app_config
  FOR SELECT TO authenticated
  USING (true);

-- =============================================================================
-- Permisos de tabla
-- =============================================================================
GRANT SELECT ON TABLE staging.colegios TO anon, authenticated;
GRANT SELECT ON TABLE staging.app_config TO anon, authenticated;
